# Generated by Django 4.2.6 on 2023-11-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='Parcelle',
        ),
    ]
