# Generated by Django 4.2.6 on 2023-11-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_fertigation_date_alter_fertile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertigation',
            name='ammonitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertigation',
            name='calcium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertigation',
            name='case1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertigation',
            name='case2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertigation',
            name='map',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertigation',
            name='organique',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertigation',
            name='qté_eau',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertigation',
            name='sulfate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertile',
            name='destination',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertile',
            name='entree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertile',
            name='s_initial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertile',
            name='s_restant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertile',
            name='sortie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
