# Generated by Django 4.2.6 on 2023-11-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_fertigation_ammonitrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertile',
            name='destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
