# Generated by Django 4.2.6 on 2023-11-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_fertile_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertile',
            name='destination',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
