# Generated by Django 4.2.6 on 2023-11-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_fertile_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertigation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fertile',
            name='name',
        ),
        migrations.AddField(
            model_name='fertigation',
            name='domaine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fertile',
            name='domaine',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
