# Generated by Django 4.2.6 on 2023-11-15 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_alter_fertile_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phytos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('varieté', models.CharField(choices=[('Nules', 'Nules'), ('Bruno', 'Bruno'), ('Orograndé', 'Orograndé'), ('Clémentine', 'Clémentine'), ('Nour', 'Nour'), ('Laarache', 'Laarache'), ('Nadorcott', 'Nadorcott'), ('Navel', 'Navel'), ('Maroc_late', 'Maroc_late'), ('Salustiana', 'Salustiana'), ('Citron', 'Citron'), ('W.sanguine', 'W.sanguine'), ('Pomelo', 'Pomelo')], max_length=50)),
                ('parcelle', models.CharField(max_length=50, null=True)),
                ('horaire', models.CharField(max_length=50, null=True)),
                ('produit', models.CharField(choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movento', 'Movento'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre'), ('Nissorun', 'Nissorun'), ('Tridicorp Jaguar', 'Tridicorp Jaguar'), ('Twinteck zin+mn', 'Twinteck zin+mn'), ('Fengib', 'Fengib'), ('Ariatox', 'Ariatox'), ('Kimia', 'Kimia'), ('Proximo', 'Proximo')], max_length=50)),
                ('matiére_avtive', models.CharField(max_length=50, null=True)),
                ('ennemi_ciblé', models.CharField(choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movento', 'Movento'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre'), ('Nissorun', 'Nissorun'), ('Tridicorp Jaguar', 'Tridicorp Jaguar'), ('Twinteck zin+mn', 'Twinteck zin+mn'), ('Fengib', 'Fengib'), ('Ariatox', 'Ariatox'), ('Kimia', 'Kimia'), ('Proximo', 'Proximo')], max_length=50)),
                ('qté_produits', models.CharField(choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movento', 'Movento'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre'), ('Nissorun', 'Nissorun'), ('Tridicorp Jaguar', 'Tridicorp Jaguar'), ('Twinteck zin+mn', 'Twinteck zin+mn'), ('Fengib', 'Fengib'), ('Ariatox', 'Ariatox'), ('Kimia', 'Kimia'), ('Proximo', 'Proximo')], max_length=50)),
                ('outiel', models.CharField(choices=[('citerne atomiseur', 'citerne atomiseur'), ('citerne manuelle', 'citerne manuelle'), ('citerne_a_dos', 'citerne_a_dos')], max_length=50)),
                ('ouvries', models.CharField(choices=[('citerne atomiseur', 'citerne atomiseur'), ('citerne manuelle', 'citerne manuelle'), ('citerne_a_dos', 'citerne_a_dos')], max_length=50)),
                ('temperature', models.CharField(choices=[('citerne atomiseur', 'citerne atomiseur'), ('citerne manuelle', 'citerne manuelle'), ('citerne_a_dos', 'citerne_a_dos')], max_length=50)),
                ('météo', models.CharField(choices=[('calme', 'calme'), ('vent', 'vent'), ('nuage', 'nuage'), ('pluie', 'pluie')], max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
