# Generated by Django 4.2.6 on 2023-11-25 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_phytos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpasswword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('domaine', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='phytos',
            name='ennemi_ciblé',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='phytos',
            name='outiel',
            field=models.CharField(choices=[('citerne_atomiseur', 'citerne_atomiseur'), ('citerne_manuelle', 'citerne_manuelle'), ('citerne_a_dos', 'citerne_a_dos')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phytos',
            name='ouvries',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phytos',
            name='qté_produits',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phytos',
            name='temperature',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Pestice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('s_initial', models.IntegerField(blank=True, null=True)),
                ('entree', models.IntegerField(blank=True, null=True)),
                ('sortie', models.IntegerField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('s_restant', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
