# Generated by Django 4.2.6 on 2023-11-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_userpasswword_alter_phytos_ennemi_ciblé_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpasswword',
        ),
    ]
