# Generated by Django 4.2.6 on 2023-11-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_userpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassword',
            name='domaine',
        ),
    ]
