# Generated by Django 4.2.6 on 2023-12-02 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_remove_userpassword_domaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producteur', models.CharField(max_length=50, null=True)),
                ('date1', models.DateField(null=True)),
                ('date2', models.DateField(null=True)),
                ('amm', models.IntegerField(blank=True, null=True)),
                ('map', models.IntegerField(blank=True, null=True)),
                ('sulf', models.IntegerField(blank=True, null=True)),
                ('nitr', models.CharField(blank=True, max_length=50, null=True)),
                ('calc', models.IntegerField(blank=True, null=True)),
                ('champ', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
