# Generated by Django 4.2.6 on 2023-12-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_ordereng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertigation',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fertile',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordereng',
            name='date1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordereng',
            name='date2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pestice',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phytos',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
