# Generated by Django 4.2.6 on 2023-12-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0002_photo_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
